services:
  front:
    container_name: front
    working_dir: /app
    image: node:20-alpine
    restart: always
    command: sh -c "npm ci && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    tty: true

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: google-like
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es-node1
    environment:
      - cluster.name=pdf-cluster
      - node.name=node1
      - network.host=0.0.0.0
      - transport.publish_host=10.104.126.159
      - http.port=9200
      - transport.port=9300
      - discovery.seed_hosts=10.104.126.159,10.104.126.129,10.104.126.60,10.104.126.189,10.104.126.67
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.initial_master_nodes=node1,node2,node3,node4,node5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/node1:/usr/share/elasticsearch/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
